### ISSUE TITLE
deprecated version of puppeteer

### ISSUE THREAD

**Issue by ousmorez** [simologos/docusaurus-plugin-papersaurus#10]
This package uses puppeteer version 10.4.0, I tried to install docusaurus-plugin-papersaurus but failed.
Puppeteer 10.4.0 is deprecated.
https://www.npmjs.com/package/puppeteer/v/10.4.0

Also getting the following message from npm:

```javascript
npm WARN deprecated puppeteer@10.4.0: Version no longer supported. Upgrade to @latest
```

**Comment by simologos** [comment]
puppeteer is upgraded
