### ISSUE TITLE
react 18 compatibility?

### ISSUE THREAD

**Issue by caradragos95** [simologos/docusaurus-plugin-papersaurus#14]
<img width="758" alt="Screenshot 2024-01-05 at 14 19 08" src="https://github.com/simologos/docusaurus-plugin-papersaurus/assets/104777859/7bdcb7fb-cebe-441a-b46d-17192d4a4232">
<img width="1056" alt="Screenshot 2024-01-05 at 14 19 56" src="https://github.com/simologos/docusaurus-plugin-papersaurus/assets/104777859/8de020d4-56ec-4067-bba7-70b2e9475e5c">

**Comment by simologos** [comment]
Hi @caradragos95,
Thanks for reporting this.

Support for Docusaurus V3 is becoming a priority for us, but right now I'm not able to tell exactly when we'll have a release for V3.

**Comment by simologos** [comment]
Papersaurus no longer requires react, hence closing this issue.
