### ISSUE TITLE
No pdf is generated

### ISSUE THREAD

**Issue by ar-to** [simologos/docusaurus-plugin-papersaurus#2]
Thanks for making this plugin.

Followed all the steps and tried different configs to see what I may be missing but nothing. I see the `pdfs` folder created inside the `build` directory but no pdfs. I even see the button add to the top of the header (right side) which was a nice touch. 

![Screen Shot 2022-01-30 at 2 53 19 AM](https://user-images.githubusercontent.com/23410938/151693154-66da9926-dc45-4495-a600-8590a68d5452.png)

![Screen Shot 2022-01-30 at 2 52 26 AM](https://user-images.githubusercontent.com/23410938/151693139-c0d1bc00-634c-4005-bd89-009c8eb2d72b.png)

![Screen Shot 2022-01-30 at 2 54 33 AM](https://user-images.githubusercontent.com/23410938/151693191-704c576c-79c2-4112-9c7b-6aca0a43b456.png)

Very promising plugin but just need some clarification to know why its not generating pdfs. Thanks

**Comment by techfreak01** [comment]
Hi ar-to

After the line `[papersaurus] Processing version 'next' you should see lines like...

```
[papersaurus] Reading file C:\...\website\build\docs\index.html
[papersaurus] Reading file C:\...\website\build\docs\a-document-id\index.html
[papersaurus] Reading file C:\...\website\build\docs\another-document-id\index.html
...
[papersaurus] Creating PDF C:\...\website\build\pdfs\root-document-id.pdf...
[papersaurus] Creating PDF C:\...\website\build\pdfs\a-document-id.pdf...
[papersaurus] Creating PDF C:\...\website\build\pdfs\another-document-id.pdf...
```

...for each item in sidebar file and the corresponding index.html file in the docs folder structure.

It looks like there goes something wrong while walking through the sidebar file and matching the corresponding index.html files in the docs folder.

Do you have the generated folders with index.html files in the docs folder (one folder with index.html file for each item/markdown file, except of the root document that doesn't have its own folder and is directly in the docs folder)?

What version of docusaurus are you using?

What does your configuration and sidebar file look like?

Regards, Matthias

**Comment by ar-to** [comment]
Hello @techfreak01,

Thanks for the reply and apologies for the late response. 

Here are a few screenshots to confirm I'm running the basic structure and on the latest docusaurus.

![dependencies](https://user-images.githubusercontent.com/23410938/153131686-ff8b248f-cba4-4ee8-bd07-059cf80076f0.png)

![build structure](https://user-images.githubusercontent.com/23410938/153131837-70202987-d046-44ff-9ecf-4a85e2c54fb0.png)

![sidebar](https://user-images.githubusercontent.com/23410938/153134018-f89ab5f4-b9a6-48b3-ab5e-4ae8263e5d29.png)

I did try learning to tweak the sidebar but I'm not sure what it should look like to make it work like the autogenerated one. Are you saying this plugin does not work with the autogenerated sidebar but I need a custom one?

**Comment by ar-to** [comment]
update:

Playing around with it more, it started to work. Here are my steps and I think its worth a PR to update the readme some how to make it more explicit. Will try to create one for the below instructions if others find it helpful.

**Steps**

1. Setup docusaurus 2 default website via their website. Then install and setup this plugin as described in the README.md
2. comment out the autogenerated and default sidebar from docusaurus upon initial setup. Then start crafting you're own custom sidebar. **This seems to indicate that this plugin does not currently support the auto-generated sidebar that comes by default with docusaurus 2 but not sure**.

```js
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['test', 'intro'],
    },
  ],
};

module.exports = sidebars;
```
3. from the default `docusaurus.config.js` make sure your have the correct sidebar name to match.
```js
const config = {
 ...
  plugins: [
    [
      "docusaurus-plugin-papersaurus",
      {
        keepDebugHtmls: false,
        sidebarNames: ["tutorialSidebar"],
        rootDocIds: [{ version: "default", rootDocId: "start_overview" }],
        addDownloadButton: true,
        autoBuildPdfs: true,
        downloadButtonText: "Download as PDF",
        ignoreDocs: ["licenses"],
        stylesheets: [],
        scripts: [],
        coverPageHeader: `...`,
        coverPageFooter: `...`,
        getPdfCoverPage: (siteConfig, pluginConfig, pageTitle, version) => {
          return `...`;
        },
        getPdfPageHeader: (siteConfig, pluginConfig, pageTitle) => {
          return `...`;
        },
        getPdfPageFooter: (siteConfig, pluginConfig, pageTitle) => {
          return `...`;
        },
        author: "Author name",
        footerParser: /© Your company\d{4}-\d{2}-\d{2}Page \d* \/ \d*/g,
      },
    ],
  ],
};
```

4. run docusaurus on the dev server via `yarn start ` to check, but here too it does not seem to actually download but it does show the expected name of the pdf. Not sure if this is on purpose or a missing feature.

![Screen Shot 2022-02-09 at 12 55 20 AM](https://user-images.githubusercontent.com/23410938/153137873-72a224f7-4a83-4219-8f60-505f0f2951e2.png)

![Screen Shot 2022-02-09 at 12 55 26 AM](https://user-images.githubusercontent.com/23410938/153137899-320ff5d9-9ecb-4cd7-916a-f5c1f996ff06.png)

5. to get the actual download to work properly I ran the build manually and then served via an actual http server.

```shell
➜  my-website yarn build
yarn run v1.22.5
$ docusaurus build
[INFO] [en] Creating an optimized production build...

✔ Client
  

✔ Server
  Compiled successfully in 23.75s


✔ Client
  

● Server █████████████████████████ cache (99%) shutdown IdleFileCachePlugin
 stored

[papersaurus] Execute generatePdfFiles...
[papersaurus] Clean pdf build folder '/Users/aricode0/devTests/docusaurus/my-website/build/pdfs'
[papersaurus] No versions.js file found. Continue without versions.
[papersaurus] Server started at http://127.0.0.1:50537/
[papersaurus] Processing version 'next'
[papersaurus] Sidebar file '/Users/aricode0/devTests/docusaurus/my-website/sidebars.js' loaded.
[papersaurus] Start processing sidebar named 'tutorialSidebar' in version 'next'
[papersaurus] Reading file /Users/aricode0/devTests/docusaurus/my-website/build/docs/test/index.html
[papersaurus] Reading file /Users/aricode0/devTests/docusaurus/my-website/build/docs/intro/index.html
[papersaurus] Creating PDF /Users/aricode0/devTests/docusaurus/my-website/build/pdfs\tutorial-test.pdf...
[papersaurus] Creating PDF /Users/aricode0/devTests/docusaurus/my-website/build/pdfs\tutorial-intro.pdf...
[papersaurus] Creating PDF /Users/aricode0/devTests/docusaurus/my-website/build/pdfs\tutorial.pdf...
[papersaurus] Creating PDF /Users/aricode0/devTests/docusaurus/my-website/build/pdfs\docusaurus.pdf...
[papersaurus] generatePdfFiles finished!
[SUCCESS] Generated static files in build.
[INFO] Use `npm run serve` command to test your build locally.
✨  Done in 45.38s.
```
via http server

```shell 
➜  my-website npx http-server ./build
Starting up http-server, serving ./build

http-server version: 14.1.0

http-server settings: 
CORS: disabled
Cache: 3600 seconds
Connection Timeout: 120 seconds
Directory Listings: visible
AutoIndex: visible
Serve GZIP Files: false
Serve Brotli Files: false
Default File Extension: none

Available on:
  http://127.0.0.1:8080
  http://192.168.0.134:8080
Hit CTRL-C to stop the server
```
6. then trying http://localhost:8080/docs/intro and the download button works now. 
7. note, running 
```shell
npx docusaurus papersaurus:build
```
did generate the pdf files as expected but when I served via the http-server, it seems like the build was cached or just not done. This is probably because this command only runs the pdf plugin but the build command threw me off for a minute until I just built via yarn and let this plugin run automatically.

Overall, glad it works but the instructions above are not as obvious as they appear to be. It could be that I'm new to using docusaurus too.

**Comment by ar-to** [comment]
closing issue since I got this working with the above instructions. Forgot to do it above.
