### ISSUE TITLE
No pdf output in the build/pdf/ directory 

### ISSUE THREAD

**Issue by George330** [simologos/docusaurus-plugin-papersaurus#3]
Hi, thank you for your work with this plugin! :) 

I wanted to test it and stumbled on an issue i.e. after runnning `npm run build`, the script doesn't produce any pdfs in the pdf folder. It says it finished: 

```
[papersaurus] Execute generatePdfFiles...
[papersaurus] Clean pdf build folder '/home/george/Desktop/my-website/build/pdfs'
[papersaurus] No versions.js file found. Continue without versions.
[papersaurus] Server started at http://127.0.0.1:43093/
[papersaurus] Processing version 'next'
[papersaurus] Sidebar file '/home/george/Desktop/my-website/sidebars.js' loaded.
[papersaurus] Start processing sidebar named 'sidebars.js' in version 'next'
[papersaurus] Sidebar 'sidebars' doesn't exist in version 'next', continue without it...
[papersaurus] generatePdfFiles finished!
```
Steps to recreate the issue: 
1. run npx create-docusaurus@latest my-website classic
2. copy the text below into `docusaurus.config.js`
```
 plugins: [
    [
      'docusaurus-plugin-papersaurus',
      {
        keepDebugHtmls: false,
        sidebarNames: ['sidebars.js'],
        rootDocIds: [
          { version: 'default', rootDocId: 'start_overview'}
        ],
        addDownloadButton: true,
        autoBuildPdfs: true,
        downloadButtonText: 'Download as PDF',
        ignoreDocs: ['licenses'],
        stylesheets: [],
        scripts: [],
        coverPageHeader: `...`,
        coverPageFooter: `...`,
        getPdfCoverPage: (siteConfig, pluginConfig, pageTitle, version) => {
          return `...`;
        },
        getPdfPageHeader: (siteConfig, pluginConfig, pageTitle) => {
          return `...`;
        },
        getPdfPageFooter: (siteConfig, pluginConfig, pageTitle) => {
          return `...`;
        },
        author: 'Author name',
        footerParser: /© Your company\d{4}-\d{2}-\d{2}Page \d* \/ \d*/g,
      },
    ],
  ], 
```
3. npm run build

**Comment by techfreak01** [comment]
Your parameter for “sidebarnames” is wrong.
It should not be the filename “sidebars.js”, but the name of the sidebar as configured inside of that file sidebars.js.

**Comment by jpsimonis** [comment]
I have the same issue. 

**my config**
 
plugins: [
    [
      'docusaurus-plugin-papersaurus',
      {
        keepDebugHtmls: true,
        sidebarNames: ['tutorialSidebar'],
        rootDocIds: [
          { version: 'default', rootDocId: 'home'},
          { version: '1.x', rootDocId: 'home'}
        ],
        addDownloadButton: true,
        autoBuildPdfs: true,
        downloadButtonText: 'Download as PDF',
        ignoreDocs: ['licenses'],
        stylesheets: [],
        scripts: [],
        coverPageHeader: `...`,
        coverPageFooter: `...`,
        getPdfCoverPage: (siteConfig, pluginConfig, pageTitle, version) => {
          return `...`;
        },
        getPdfPageHeader: (siteConfig, pluginConfig, pageTitle) => {
          return `...`;
        },
        getPdfPageFooter: (siteConfig, pluginConfig, pageTitle) => {
          return `...`;
        },
        author: 'Author name',
        footerParser: /© Your company\d{4}-\d{2}-\d{2}Page \d* \/ \d*/g,
      },
    ],
  ],
  
Build Output:
no file in build directory filesystem

npx docusaurus papersaurus:build

[papersaurus] Execute generatePdfFiles...
[papersaurus] Clean pdf build folder 'C:\vscode\DQA Internal Documentation\site\build\pdfs'
[papersaurus] Server started at http://127.0.0.1:49787/
[papersaurus] Processing version 'next'
[papersaurus] Sidebar file 'C:\vscode\DQA Internal Documentation\site/sidebars.js' loaded.
[papersaurus] Start processing sidebar named 'tutorialSidebar' in version 'next'
[papersaurus] Processing version '1.0.0'
[papersaurus] Sidebar file 'C:\vscode\DQA Internal Documentation\site/versioned_sidebars/version-1.0.0-sidebars.json' loaded.
[papersaurus] Start processing sidebar named 'tutorialSidebar' in version '1.0.0'
[papersaurus] generatePdfFiles finished!

**Comment by jpsimonis** [comment]
fyi: i also have autogenerated sidebars

**Comment by techfreak01** [comment]
Please look into the solution found by ar-to in [issue 2](https://github.com/simologos/docusaurus-plugin-papersaurus/issues/2).

Auto generated sidebars don't work with this plugin. You should create a custom sidebar.

**Comment by techfreak01** [comment]
﻿Your parameter “sidebarnames” is wrong.
It should not be the filename sidebars.js, but the name of the sidebar as configured inside of that file sidebars.js.




Von meinem iPhone gesendet
