### ISSUE TITLE
PDF downloads with HTML content but is not loadable by any PDF viewers

### ISSUE THREAD

**Issue by donjmilligan** [simologos/docusaurus-plugin-papersaurus#4]
We are able to download PDFs using the download button, but the file does not open in web browsers or Document Viewer in Ubuntu linux. 

Opening in Document Viewer results in an error: `File type HTML document (text/html) is not supported` even though the file has a PDF extension. 

Viewing the file in a text editor reveals that it is only HTML content. Here is a look a the start of the file 
```
<!doctype html>
<html lang="en" dir="ltr" class="docs-wrapper docs-doc-page docs-version-1.0.0 plugin-docs plugin-id-default docs-doc-id-index">
<head>
``` 

It also ends with a closing HTML element.

**Comment by simologos** [comment]
Hi donjmilligan,

Do you have a reproducible example repo somewhere?
And how exactly did you generate the PDFs?

Thanks!

**Comment by donjmilligan** [comment]
Hi [simologos](https://github.com/simologos)

We have docusaurus running on a machine in AWS and built using an Azure Dev Ops pipeline. We have the plugins (including [Puppeteer](https://pptr.dev/)) installed using the instructions in this repo, and we are using the download PDF button option. 

Please let me get back to you tomorrow after i have talked to my team about either sharing access to the site, or a version of our code with you.

**Comment by donjmilligan** [comment]
I have been asked to close this en lieu of using an external solution another of our own teams has built. Sorry for the hassle.
