### ISSUE TITLE
Allow customization of 30000ms timeout

### ISSUE THREAD

**Issue by jsphstls** [simologos/docusaurus-plugin-papersaurus#7]
Thank you for making this plugin!

```
[ERROR] TimeoutError: waiting for Page.printToPDF failed: timeout 30000ms exceeded
```

Puppeteer supports a `timeout` option that could be exposed as an option of this plugin:
https://stackoverflow.com/questions/69436420/how-to-increase-timeout-for-pupetteers-page-pdf-when-getting-timeouterror-wai

**Comment by simologos** [comment]
Thank you for the suggestion. I think this is a good idea!

**Comment by simologos** [comment]
The puppeteer Timeout is now configurable. See `puppeteerTimeout` in the readme file.
